### ISSUE TITLE
Why is the database not builded in Dockerfile ?

### ISSUE THREAD

**Issue by kopax** [etalab/addok-docker#19]
Hi and thansk for sharing, I was just wondering, why does the `Dockerfile` not including the database by default and why those manuals steps?

```Dockerfile
FROM etalab/addok

RUN wget https://adresse.data.gouv.fr/data/ban/adresses-odbl/latest/addok/addok-france-bundle.zip
RUN mkdir /data
RUN unzip -d /data addok-france-bundle.zip
RUN mv /data/addok.conf /etc/addok/addok.conf
```

Something like this will this cause issue? Thanks & Best!

**Comment by jdesboeufs** [comment]
Because it's too long, and we don't want users have to do this, or deal with big images.
But we can provide our code to do the same thing, for the expert only.

You have to know that we use this project to help administrations/companies to leverage our tools, the most efficiently as possible.

Soon, the dataset will be updated daily (currently weekly).
